### ISSUE TITLE
Can't build it. Linker command failed with exit code 1

### ISSUE THREAD

**Issue by Mefistophell** [loothood/ping_pong_multiplayer#4]
Hello! 
I tried to build it but got errors:
`note: "cc" "-m64" "-arch" "x86_64"`
`note: ld: library not found for -lSDL2`

Maybe you have ideas why that happened? 
Thanks!

**Comment by loothood** [comment]
what OS do you use?

**Comment by Mefistophell** [comment]
Thanks! That was a problem. 

To build it on MacOS you should have `sdl2` installed.
It can be done by running this one:  

`brew install sdl2`
